Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,6 +24,17 @@ jobs:
         uses: actions/setup-python@v2.2.1
         with:
           python-version: 3.8.x
+		  
+	  
+        run: |
+          for file in $(find . -name '*.sql'); do
+            # Check if the filename follows versioning conventions (e.g., v1.0.0__insert_script.sql)
+            if ! [[ $(basename "$file") =~ ^v\d+\.\d+\.\d+__[a-zA-Z0-9_]+\.sql$ ]]; then
+              echo "Error: Invalid versioning convention in file $file"
+              exit 1
+            fi
+		  done
+  
 
       - name: Run schemachange
         env:
